#!/usr/bin/env bash
set -eo pipefail

base_template() {
  pr_template="$(dirname "$0")/.github/pull_request_template.md"
  echo "$pr_template"
}

main_branch() {
  git remote show "origin" | grep 'HEAD branch' | cut -d' ' -f5
}

commit_msgs() {
  local main="$1"
  git log --format=format:'- %s' "$main..$(git branch --show-current)"
}

create_pr_template() {
  local main="$1"
  pr_template=$(mktemp --tmpdir gh-create-pr.XXXXXX)
  msgs_file=$(mktemp --tmpdir gh-create-pr.XXXXXX)
  trap 'rm -f "$pr_template" "$msgs_file"' EXIT
  msgs=$(commit_msgs "$main")
  printf '%s\n' "$msgs" >"$msgs_file"
  awk -v msgs_file="$msgs_file" '/@COMMIT_MSGS@/{while ((getline line < msgs_file) > 0) print line; close(msgs_file); next}1' "$(base_template)" >>"$pr_template"
  echo "$pr_template"
}

{
  main="$(main_branch)"
  pr_template=$(create_pr_template "$main")
  pr_title="$(commit_msgs "$main" | tail -n 1)"
  pr_title="${pr_title/#- /}"

  declare -a gh_args
  gh_args+=("--body-file")
  gh_args+=("$pr_template")
  gh_args+=("--title")
  gh_args+=("$pr_title")
  gh pr create "${gh_args[@]}" "$@"
}
