#!/usr/bin/env bash
set -eo pipefail

export GH_PAGER="cat"

BASEDIR=$(dirname "$(realpath "$0")")
#shellcheck disable=SC1091
source "$BASEDIR/ghcli-common.sh"

#shellcheck disable=SC2154
usage() {
  local exit=${1:-1}
  cat <<EOF

Usage: gh-mass-dependabot

Approves and (optionally) merges everything that matches a string and is by dependabot

Flags
  -f, --filter - the search string (required)
  -m, --squash-merge - do a merge after approving
EOF
  exit "$exit"
}

{
  searchString=""
  merge_pr="false"
  ARGS=$(getopt --options 'f:hm' --longoptions 'filter:,help,squash-merge' -- "${@}")
  eval "set -- ${ARGS}"
  while true; do
    case "${1}" in
    --filter | -f)
      searchString="${2}"
      shift 2
      ;;
    --squash-merge | -m)
      merge_pr="true"
      shift
      ;;
    -h | --help)
      usage "0"
      ;;
    --)
      shift
      break
      ;;
    *)
      usage
      ;;
    esac
  done
  if [[ -z "$searchString" ]]; then
    usage
  fi
  while read -r line; do
    login=$(echo "$line" | jq -r '.login')
    isDraft=$(echo "$line" | jq -r '.isDraft')
    title=$(echo "$line" | jq -r '.title')
    status=$(echo "$line" | jq -r '.statusRollup')
    url=$(echo "$line" | jq -r '.url')
    if [[ "$status" == "SUCCESS" && "$isDraft" == "false" && "$login" == "dependabot" ]]; then
      if [[ "$title" == *"${searchString}"* ]]; then
        echo "ℹ️ $url"
        gh pr review --approve "$url"
        if [[ "$merge_pr" == "true" ]]; then
          gh squash-merge "$url" --use-default-msg
        fi
      fi
    fi
  done <<<"$(gh my prs -aj)"
}
