#!/usr/bin/env bash
#
set -eo pipefail

export GH_PAGER="cat"

BASEDIR=$(dirname "$(realpath "$0")")
#shellcheck disable=SC1091
source "$BASEDIR/ghcli-common.sh"

# Selects failed jobs from the status_rollup with some dodgy capturing
# output to be {"runId":"24521981319","jobId":"71682061689"}
JQ_FAILED_JOBS='.[] | select ( .conclusion=="FAILURE" ) | .detailsUrl | capture("/runs/(?<runId>[0-9]+)/job/(?<jobId>[0-9]+)")'

__retry_failed_jobs() {
  local pr_number="$1"
  local runId
  local jobId
  local job_id_jsonlines=()

  mapfile -t job_id_jsonlines < <(gh pr view "$pr_number" --json "statusCheckRollup" --jq '.statusCheckRollup' | jq -c "$JQ_FAILED_JOBS")
  for jsonline in "${job_id_jsonlines[@]}"; do
    runId=$(echo "$jsonline" | jq -r ".runId")
    jobId=$(echo "$jsonline" | jq -r ".jobId")
    echo "🔎 ... Retry $jobId in $runId"
    gh run rerun --job "$jobId"
  done
}

#shellcheck disable=SC2154
usage() {
  local exit=${1:-1}
  cat <<EOF

Usage: gh-pr-job-retry 'pr'

Retries all the failed jobs for that PR.

EOF
  exit "$exit"
}

{
  PR=$1 || true
  if [[ -z "$PR" ]]; then
    usage
  fi
  __retry_failed_jobs "$PR"
}
