#!/usr/bin/env bash
set -eo pipefail

export GH_PAGER="cat"

BASEDIR=$(dirname $(realpath "$0"))
#shellcheck disable=SC1091
source "$BASEDIR/ghcli-common.sh"

pr_search() {
  queryString="repo:$1 is:open is:pr review-requested:@me archived:false"
  # shellcheck disable=SC2016
  query='query ($searchQuery: String!, $endCursor: String) {
          search(query: $searchQuery, after: $endCursor, type: ISSUE, first: 50) {
            edges {
              node {
                ... on PullRequest {
                  number
                  title
                  author {
                     login
                  }
                  createdAt
                  url
                }
              }
            }
            pageInfo {
              hasNextPage
              endCursor
            }
          }
        }'
  gh api graphql --paginate -F searchQuery="$queryString" --raw-field query="$(compressQuery "$query")"
}

usage() {
  cat <<EOF

Usage: gh-unassign <repo>

Removes you as a reviewer on all the PRs raised by dependabot
in a given repo.

EOF
  exit 1
}

REPO=$1 || true

if [[ -z "$REPO" ]]; then
  usage
fi

me=$(gh_whoami)
pr_list=$(pr_search "$REPO" | jq -r -c '.data.search.edges | .[] | select(.node.author.login == "dependabot") | { "pr" : .node.number, "url" : .node.url }')
for json in $pr_list; do
  pr=$(echo "$json" | jq -r .pr)
  url=$(echo "$json" | jq -r .url)
  echo "Removing $me from $url"
  gh_api --method DELETE "repos/$REPO/pulls/$pr/requested_reviewers" \
    --silent \
    -f "reviewers[]=$me"
done
