#!/usr/bin/env bash
set -eo pipefail

export GH_PAGER="cat"

BASEDIR=$(dirname $(realpath "$0"))
#shellcheck disable=SC1091
source "$BASEDIR/ghcli-common.sh"

usage() {
  cat <<EOF

Usage: gh-wf-pr-approval

Sets the defaults such that github actions may approve & create PRs
on all your public repos.

EOF
  exit 1
}


while getopts 'h' flag; do
  case "${flag}" in
  h) usage ;;
  *) usage ;;
  esac
done

me=$(gh_whoami)
repos=$(gh repo list "$me" --visibility public --no-archived --json "nameWithOwner" -q ".[].nameWithOwner")
for repo in $repos; do
  echo "Setting $repo"
  gh_api --method PUT "repos/$repo/actions/permissions/workflow" -F can_approve_pull_request_reviews=true
done
